sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product dmtn-133
env:
  global:
    -
      # LTD_AWS_ID
      secure: WbMUWu6Ke0+h6X2KlIHPzto8WF4z40LYgoavZBixTaPoKb3m/zbi+UpUQkQ2TZ6+cpHQd2FJHhcPc8aCMKeRMSI0Qw6MFBzYgXA3kn5WKmu63ot/A9sVR7JCBWafW7PcbFGiQIj0N1lh0iJW2Jco0+6C6ulI69vNWQCyUoD40bymIayAxiHWA8zGjyhWa8U/co9uqXDqzWjvf/1lOxWVeUx/FwHlh6+NYHoRpxt2hemvN/prkCfw7z68+ueT4h641vryE5WKO0IJT+uRvQYsyEpFmWdRsijr43fC0YCywilxkg/o4WxsGngZ392xoQElf60GAZ3MtW0uvtHvtsY3jZQUpKpN1V1exsvDRwhOiIuDy/8WYvxaMou5eSTGVlCXPzBGszlLX5TMv/4ftd7ibo4DwuGeQgZJ2hnnfkdpOr2HibzwRqwZnqrXqn/ujxBpczDHAEm0+w0GLTz+IBRUist+oOPzRIoYeg5IpEPIR4wUcigzmGls89gso/limOiLaoNRYQfUgvCju1Q2vllLv0kaO4Kujb2zqi9k7p49L7OdAruyOjRvit0hfEI2FWXb/mdpJKuDZnS+RufltcgCSlJfm7Lrp5Wm7UUQIUdrPrkxKwLUCR7Pe+lWZKQkgOCgoV/iP3Y6LnsAo/FmsFpSJXXwr5a/pT+2VbVCKyrKXVU=
    -
      # LTD_AWS_SECRET
      secure: aRemVRTLLDyDNECCV/1Tfz/vH2bSl0ZmK86B29qN8eBDuSorKNw/qwnR8j6iHuYQMcfuqj/IelyczdnHbi5m9gN0lQLDxL5gKeZ93c0yxlYlwi007pArrYmHBOf8jz4S2AAd4mQQ0Ne3SJGSuooVyQgv+jjrdViGkIXxUTYOFyjro5eAaLe+8thSvCTAyusO/53Ieu/JZYi2Ln0alLm2OW2Yvo+2eRDrCIaIeTxxo/wHVwkQ6fgYoVusWe6t1TPDBIkXt84UcjokrQ3t4MlJjz7Big8NPSUpINqaA9Jec41feI1KK0wSd6Ve71B82NgrtiGY1uMDIOBH+N3uXM8q8BdlXQvqu3TyWypCc2RnzxaMtUL6gqHZ+96Zk9bNXKWLoHNy8z/SWEgb4aBqoZlfYjsT0oYvvqKtJ9rs7fwzj0/onNOXkkg6MLuXiFHOxmyWeJIl6m7we/O9/LA64J92z1HYlWj7FFK1XF+n3utyTVrOmeCUimVSCNdM/lWWGL58jZVcWMZmXLS/zYVoQqc7qMqh/lyMhXK+s5FU6LpkmARmTvqWED7/EUIOcrl1DdcPzvdfY/5ndpQncrU3DIY3yIcY3F4gtB/z+R5UU6FwmvsrCWYoCJ40bBwt67mChTgjswgqEX+GsmNDw6gFOCnD9sQP8+zkm5akDPwugc8xJN4=
    -
      # LTD_USERNAME
      secure: Pf9lyOvKbuiwdgBjZPifFM9h8fas7iqQHFM43enwazG2E4cDc9J47hW2yX3lY3HGR8yStRL0bNLF/mKFuXGufdcgzDRPPV1XaDNnEzsLsU34Snm28xnaDcyodVA4xosmoHOkIhOyjSZf2LkVOvPAikWYd11Wu6gkL+xca1TOvdvyb0v65ZbKYHeu03CUYx+Vc9VHGqOEZ8QORDBw0Qn1RQ8v3kUXyEoU84riFE3yNusnvxUW/mYwuc6IwOuR+Al6xcP02Ej1e2qrE8eNV9Q9D03JLsovKsGECughduTgD3XIKVvpGDyLcbkTHIVYmFQ0JZPJ6sKdV0b4AxFo20RCAvVtvZRYrJ6Wmj91qJRdtroAukKLtiCUGlpNqjBV/+09+vuFXpbOxEjZO7c2eQQz/cE8gT+p6/4//EHcEUpJ3yntp13n8uR0J0u1ccqFOSnvJG0AsAXJVbGqqDu0WvoggZYHfxCejaQ6SBPV+jQJiCFEL3Mb24fVTwpd5lhFk4RzXsupunuAHnP4i+GfaBLEIunnxYWj+6KQFX2OWJykbNC3Spo1nObVGcI0C8RVwLu3BCoMs/hyU1wuJ7QVyCSpkdnUEY3LNblpQGo6FuEAVJo6MNB2sPF9fpQ707WdlQFhPdwVy8yubuWsKX/KcB22wk2QXJP8A4iji9NTdaqygAk=
    -
      # LTD_PASSWORD
      secure: zMNVnTQG9HS7v9D6O/2t8Mr9Ki2Lc1sxVgi11hYiBx5L6P5PWKVEjKX3sWUa2iCOwsuex3MgGP2e8RE/yhQP7XWyl7mBRr+j+P8DOfMqSu2Y622aXWV8/jCHfpfwq+5mnMi1/saL10OqiPrxQrButOilH4epDxbhIi3N8CbUaA0hks4i0b0ZBVDhDWPCnqS4D56oBd4tEgVLL6yPGJC9nudmSvZxF4gFPG/yvnAkkdWP/GMCVGK+x+Zf5bs8g4XlmDh+FfF+hb4y7Ofk/qlElAznmHepnaGHO3VdSq4S4HZBjHvO4blGU7Hb4uj8J13AoBOsezhxPzpz8jYeqoGywR1zNH+RZ7YcRYO8UdOmv6/CJXtlhE5GOnSzI9xUxrwE3k1UReKjKqGuv+8/59rlY2pbtOAMewGw8OZ9aOiNeykTw9NlcemagHIhSYgrpkxinRZ+d45pmy2xG1GQC8JkLIqL9+etmf8EhoQD1cn0ht9/B9Hit+Tl3Pv0+el5ZMWWfuN24lnQVFVr0mkZ+lv9sP1a9MWBFpRx24ugM1C5CDcp+/H1NHm3ceT80m+N7eBv7Rjf9UPQxCC8lzZrspfpUZ06hZQMkS10TulDOZcmhJdCB0HzdoCTRcnPOf1ZRXPTR4soRrYJr5qoicCxntrlyWhpMY79KCXbdTRcAi/vyVY=
